### ISSUE TITLE
有个课程不能下载

### ISSUE THREAD

**Issue by sirius-fan** [Rhilip/cn-mooc-dl#3]
http://www.icourse163.org/learn/BIT-1001870002

试试这个地址，会有error

**Comment by Rhilip** [comment]
Tell my which error you meet?
Only "error" cann't help me to find out the reason.

**Comment by sirius-fan** [comment]
好吧，my fault


 【第二周】数据分析之展示 单元6：实例2：引力波的绘制
视频: "0 “引力波的绘制”实例介绍.mp4" "http://v.stu.126.net/mooc-video/nos/mp4/2017/04/17/1006127188_9af594feff0a4e59bf377973d2fae914_shd.mp4"
视频: "1 “引力波的绘制”实例绘制（助教）.mp4" "http://v.stu.126.net/mooc-video/nos/mp4/2017/04/20/1006131155_c44d6d75242e4546bc32845fc3cb1092_shd.mp4"
文档: "DV06单元学习资料.pdf" "http://nos.netease.com/edu-lesson-pdfsrc/4F3CE9D77C244A4ED279D3EFF7AE2ED8-1492649801047?NOSAccessKeyId=7ba71f968e4340f1ab476ecb300190fa&Expires=1497321470&Signature=gnGaIZUBdzkuXjW5kVSvm6vKm3dx4oDOYeA95cDUNYA%3D&download=DV06-%E5%AE%9E%E4%BE%8B2-%E5%BC%95%E5%8A%9B%E6%B3%A2%E7%9A%84%E7%BB%98%E5%88%B6.pdf"
Traceback (most recent call last):
  File "C:\Users\fff99\Desktop\python\cn-mooc-dl-master\icourse163-dl.py", line 215, in <module>
    main(course_url)
  File "C:\Users\fff99\Desktop\python\cn-mooc-dl-master\icourse163-dl.py", line 133, in main
    lesson_name = model.clean_filename(model.raw_unicode_escape(lesson_re.group("lesson_name")))
  File "C:\Users\fff99\Desktop\python\cn-mooc-dl-master\model\download.py", line 59, in raw_unicode_escape
    return string.encode('utf-8').decode('unicode_escape').encode('gbk', 'ignore').decode('gbk', 'ignore')
UnicodeDecodeError: 'unicodeescape' codec can't decode byte 0x5c in position 0: \ at end of string
[Finished in 4.9s]

**Comment by Rhilip** [comment]
This is reason,when script try to get "富文本："引力波的绘制"实例代码" ,but the wrong lesson name `"\"` return. 
`s85.anchorQuestions=null;s85.attachments=null;s85.chapterId=1002308118;s85.contentId=1002471050;s85.contentType=4;s85.gmtCreate=1492651930132;s85.gmtModified=1496133730245;s85.id=1003189888;s85.jsonContent="{\"nosKey\":\"1C6BB42E53E59653F0FBB0DCA6C20824-1492650051135\",\"fileName\":\"grawave.zip\"}";s85.lessonId=1002796569;s85.live=null;s85.liveInfoDto=null;s85.name="\"\u5F15\u529B\u6CE2\u7684\u7ED8\u5236\"\u5B9E\u4F8B\u4EE3\u7801";s85.position=19;s85.resourceInfo=null;s85.termId=1001963001;s85.unitId=null;s85.viewStatus=5;`

As this script needn't rich text.
You can fix it temporarily by change model.download.raw_unicode_escape.
```python
def raw_unicode_escape(string: str) -> str:
    try:
        st = string.encode('utf-8').decode('unicode_escape').encode('gbk', 'ignore').decode('gbk', 'ignore')
    except UnicodeDecodeError:
        st = string
    return st
```

**Comment by sirius-fan** [comment]
Thanks!
